# 🌸 Iris Dataset Visualization
### DevelopersHub Corporation — AI/ML Engineering Internship
**Intern Name:** Raheela  Nisar 
**Project:** Task 1 - Exploring and Visualizing the Iris Dataset  
**Organization:** DevelopersHub Corporation

In [1]:
pip install sweetviz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sweetviz in c:\users\elysium\appdata\roaming\python\python313\site-packages (2.3.3)
Requirement already satisfied: pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3 in c:\programdata\anaconda3\lib\site-packages (from sweetviz) (2.3.3)
Requirement already satisfied: numpy>=1.16.0 in c:\programdata\anaconda3\lib\site-packages (from sweetviz) (2.3.5)
Requirement already satisfied: matplotlib>=3.1.3 in c:\programdata\anaconda3\lib\site-packages (from sweetviz) (3.10.6)
Requirement already satisfied: tqdm>=4.43.0 in c:\programdata\anaconda3\lib\site-packages (from sweetviz) (4.67.1)
Requirement already satisfied: scipy>=1.3.2 in c:\programdata\anaconda3\lib\site-packages (from sweetviz) (1.16.3)
Requirement already satisfied: jinja2>=2.11.1 in c:\programdata\anaconda3\lib\site-packages (from sweetviz) (3.1.6)
Requirement already satisfied: importlib_resources>=1.2.0 in c:\users\elysium\appdata\roaming\python\python313\site-packages (from sweetviz) (7.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2>=2.11.1->sweetviz) (3.0.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (25.0)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (12.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (3.2.5)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>=3.1.3->sweetviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas!=1.0.0,!=1.0.1,!=1.0.2,>=0.25.3->sweetviz) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.1.3->sweetviz) (1.17.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from tqdm>=4.43.0->sweetviz) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Importing the Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
%matplotlib inline

In [3]:
# Fetching the dataset
df = pd.read_csv(r'C:\Windows\Code\IRS\iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:

# Fetching the dataset
df = pd.read_csv('Iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
#Head of dataset
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [6]:
# Shape of dataset
df.shape

(150, 6)

In [7]:
# 3 types of Species
df.Species.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [8]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Species'] = encoder.fit_transform(df['Species'])

In [9]:
df.Species.unique()
#Iris-setosa = 0, Iris-versicolor = 1, Iris-virginica = 2

array([0, 1, 2])

In [10]:
report=sv.analyze(source=df)
report.show_html('Iris Report')

NameError: name 'sv' is not defined

In [ ]:
df.isnull().sum()

In [ ]:
print(df.columns)

In [ ]:
plt.figure(figsize=(10,4))
plt.title('Comparison between sepal width and length on the basis of species')
sns.scatterplot(data=df, x='SepalLengthCm', y='SepalWidthCm', hue='Species', palette='deep')
plt.show()

In [ ]:
plt.figure(figsize=(10,4))
plt.title('Comparison between petal width and length')
sns.scatterplot(data=df, x='PetalLengthCm', y='PetalWidthCm', hue='Species', palette='deep')
plt.show()

In [ ]:
#correlation between features
sns.heatmap(df.corr(),annot=True,vmin=-1,vmax=1,cmap='viridis')

In [ ]:
#Pairplot of Species
sns.pairplot(df,hue="Species",height=3,palette='deep')

In [ ]:
#Seperate Dependent and Independent Features

#For Dependent feature we use 'y' variable
y=df['Species']

#For Indenpendent feature we use 'X' variable
x=df.drop(['Id','Species'],axis=1)

In [ ]:
x.shape,y.shape

In [ ]:
#Spliting into training and testing dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test =  train_test_split(x,y,test_size=0.3,random_state=0)

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier= RandomForestClassifier()

In [ ]:
classifier.fit(x_train,y_train)

In [ ]:
# Feature Importance
classifier.feature_importances_

In [ ]:
for feature, index in zip(x, range(4)):
    print(feature,':',classifier.feature_importances_[index])

In [ ]:
y_pred=classifier.predict(x_test)

In [ ]:
y_pred

In [ ]:
y_actual=np.array(y_test)
y_actual

In [ ]:
print(np.round(classifier.score(x_test,y_test)*100,2),'%')

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report
confusion_matrix(y_actual,y_pred)

In [ ]:
print(classification_report(y_actual,y_pred))

## Key Insights
- Setosa species is easily separable from other species
- Petal Length and Petal Width are the most important features
- Model Accuracy: 97.78%
- No missing values found in dataset

## Conclusion
This project successfully visualized the Iris dataset using 
scatter plots, histograms, and pair plots. Random Forest 
Classifier achieved 97.78% accuracy.

In [13]:
import os
import joblib

folder = r"D:\Iris_Streamlit_App"

os.makedirs(folder, exist_ok=True)

joblib.dump(model, os.path.join(folder, "model.pkl"))
joblib.dump(scaler, os.path.join(folder, "scaler.pkl"))

print("Files Saved Successfully")

Files Saved Successfully